import type { DomainPack, ModelJobContract } from "./types";

export const coreModelJobContracts: ModelJobContract[] = [
  {
    id: "job_propose_evidence_cards",
    jobName: "propose_evidence_cards",
    inputSchema: "one document, target issue, source spans",
    outputSchema: "candidate cards with document_id, page_id/media_segment_id, span_id, exact_quote_or_excerpt",
    contextScope: "single document plus target issue",
    allowedLanes: ["local", "frontier"],
    redactionPolicy: "tokenize_pii",
    verificationPolicy: "resolve_to_cited",
    destinationPolicy: "graph_claim",
    timeoutMs: 30000,
  },
  {
    id: "job_find_contradictions",
    jobName: "find_contradictions",
    inputSchema: "issue subgraph with verified and cited cards",
    outputSchema: "contradiction pairs with both source span references",
    contextScope: "one issue theory and adjacent evidence cards",
    allowedLanes: ["frontier"],
    redactionPolicy: "tokenize_pii",
    verificationPolicy: "resolve_to_cited",
    destinationPolicy: "prep",
    timeoutMs: 60000,
    costCeilingUsd: 1,
  },
  {
    id: "job_build_meeting_brief",
    jobName: "build_meeting_brief",
    inputSchema: "verified cards, issue theories, record gaps, obligations",
    outputSchema: "brief sections whose factual statements cite verified cards",
    contextScope: "meeting-scoped verified graph slice",
    allowedLanes: ["deterministic", "frontier"],
    redactionPolicy: "cleartext_required_with_consent",
    verificationPolicy: "verified_only_destination",
    destinationPolicy: "packet",
    timeoutMs: 60000,
    costCeilingUsd: 2,
  },
  {
    id: "job_detect_prompt_injection",
    jobName: "detect_prompt_injection",
    inputSchema: "one inert source text block",
    outputSchema: "security findings with source span references",
    contextScope: "one document or transcript segment",
    allowedLanes: ["deterministic", "local"],
    redactionPolicy: "none",
    verificationPolicy: "draft",
    destinationPolicy: "brainstorm",
    timeoutMs: 5000,
  },
];

export const definitiveDomainPacks: DomainPack[] = [
  {
    id: "domain_vendor_contract",
    name: "Vendor contract / SLA dispute",
    ontologyExtension: ["UptimeCommitment", "ServiceCredit", "ChangeOrder", "InvoiceLineItem"],
    intakeChecklist: ["Master Services Agreement", "Statements of work", "Invoices", "Uptime reports", "Support tickets"],
    recordTypes: ["MSA", "SOW", "Invoice", "Uptime report", "Support ticket", "Change order", "Status report"],
    issueTemplates: [
      "Uptime committed vs uptime delivered",
      "Billing overage and service-credit eligibility",
      "Change-order authorization completeness",
    ],
    strengthRubric: ["executed contract", "direct admission", "uptime-log corroboration", "date specificity"],
    contradictionPatterns: ["sla-vs-delivery", "baseline-vs-degraded-service", "promise-vs-log"],
    missingRecordRules: ["references to uptime reports", "meeting notes not present", "attachments not present"],
    obligationPatterns: ["uptime targets", "review dates", "service-credit commitments"],
    questionTemplates: ["What record proves this service level was met?", "Will the vendor provide written confirmation?"],
    packetTemplates: ["Vendor review brief", "Mediation packet", "Records request"],
    jurisdictionNotes: ["Surface contract-specific deadlines as review notes, not legal conclusions."],
    modelJobPolicy: {
      propose_evidence_cards: ["local", "frontier"],
      find_contradictions: ["frontier"],
      build_meeting_brief: ["deterministic", "frontier"],
    },
    legalBoundaryCopy: "SourceDeck surfaces questions your contract records raise; it does not give legal advice.",
    exportFormats: ["PDF", "DOCX", "Markdown", "CSV", "JSON", "ZIP"],
    liveModeButtons: ["Copy quote", "Request written answer", "Log refusal", "Log commitment"],
  },
  {
    id: "domain_hr_workplace",
    name: "HR / workplace dispute",
    ontologyExtension: ["Complaint", "Policy", "Comparator", "InvestigationStep", "AdverseAction"],
    intakeChecklist: ["Policies", "Complaints", "HR emails", "Performance reviews", "Investigation records"],
    recordTypes: ["Policy", "Email", "Review", "Warning", "Complaint file", "Investigation note"],
    issueTemplates: ["Policy promised vs policy followed", "Stated reason changed over time"],
    strengthRubric: ["policy authority", "date sequence", "direct admission", "independent corroboration"],
    contradictionPatterns: ["policy-vs-practice", "reason-shifting", "timeline conflict"],
    missingRecordRules: ["referenced complaint not present", "attachment missing", "investigator notes missing"],
    obligationPatterns: ["response deadline", "investigation commitment", "accommodation step"],
    questionTemplates: ["Which policy section governed this step?", "What document supports that reason?"],
    packetTemplates: ["HR meeting packet", "Attorney consult packet", "Follow-up request"],
    jurisdictionNotes: ["Employment-law conclusions require counsel review."],
    modelJobPolicy: {
      propose_evidence_cards: ["local", "frontier"],
      find_contradictions: ["frontier"],
      build_meeting_brief: ["deterministic", "frontier"],
    },
    legalBoundaryCopy: "SourceDeck identifies record-supported concerns and questions to review.",
    exportFormats: ["PDF", "DOCX", "Markdown", "CSV", "JSON", "ZIP"],
    liveModeButtons: ["Copy quote", "Ask policy basis", "Log refusal", "Action item"],
  },
];

